# fly.toml app configuration file for the Colyseus server
app = "commons-game-server"
primary_region = "sjc"

[build]
  dockerfile = "apps/server/Dockerfile"

[env]
  NODE_ENV = "production"
  PORT = "2567"

[[services]]
  internal_port = 2567
  protocol = "tcp"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"

  [[services.http_checks]]
    interval = "15s"
    timeout = "2s"
    method = "get"
    path = "/health"
    protocol = "http"
