[build]
  builder = "dockerfile"
  dockerfile = "./Dockerfile"
  build_command = "docker build -t tragedy-commons-server ."

[deploy]
  start_command = "node dist/index.js"
  start_timeout = 30
  healthcheck_path = "/health"
  healthcheck_timeout = 30
